[versions]
agp = "8.2.0-alpha05"
kotlin = "1.8.10"
core-ktx = "1.10.1"
junit = "4.13.2"
androidx-test-ext-junit = "1.1.5"
espresso-core = "3.5.1"
lifecycle-runtime-ktx = "2.6.1"
activity-compose = "1.7.1"
compose-bom = "2023.05.01"
coroutines = "1.6.4"
interceptor = "4.10.0"
coil = "2.2.2"
navigation-compose = "2.5.3"
paging = "3.1.1"
paging-compose = "1.0.0-alpha20"
dagger = "2.45"
navigation = "2.5.3"
moshi = "1.14.0"
pager = "0.28.0"
extended-icons = "1.4.3"
accompanist = "0.28.0"
camera = "1.2.3"
camera-core = "1.3.0-alpha07"
mlkit = "17.1.0"
material3 = "1.4.3"
play-services-auth = "20.5.0"
firebase-auth-ktx = "22.0.0"
firebase-bom = "32.0.0"
firebase-firestore-ktx = "24.6.1"
jetFirestore = "1.0.2"

[libraries]
androidx-navigation-compose-2_5_3 = { module = "androidx.navigation:navigation-compose", version.ref = "navigation-compose" }
accompanist-navigation = { group = "com.google.accompanist", name = "accompanist-navigation-animation", version.ref = "accompanist" }
core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "core-ktx" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
firebase-bom = { group = "com.google.firebase", name = "firebase-bom", version.ref = "firebase-bom" }
firebase-jet-firestore = { group = "com.github.raipankaj", name = "JetFirestore", version.ref = "jetFirestore" }
lottie = { group = "com.airbnb.android", name = "lottie-compose", version = "5.2.0" }
kotlin-coroutines = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-core", version.ref = "coroutines" }
retrofit = { group = "com.squareup.retrofit2", name = "retrofit", version = "2.9.0" }
retrofit-moshi = { group = "com.squareup.retrofit2", name = "converter-moshi", version = "2.9.0" }
okhttp = { group = "com.squareup.okhttp3", name = "okhttp", version.ref = "interceptor" }
okhttp-logging = { group = "com.squareup.okhttp3", name = "logging-interceptor", version.ref = "interceptor" }
coilx = { group = "io.coil-kt", name = "coil-compose", version.ref = "coil" }
paging = { group = "androidx.paging", name = "paging-runtime", version.ref = "paging" }
paging-compose = { group = "androidx.paging", name = "paging-compose", version.ref = "paging-compose" }
androidx-test-ext-junit = { group = "androidx.test.ext", name = "junit", version.ref = "androidx-test-ext-junit" }
espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espresso-core" }
lifecycle-runtime-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "lifecycle-runtime-ktx" }
activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "activity-compose" }
compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "compose-bom" }
ui = { group = "androidx.compose.ui", name = "ui" }
ui-graphics = { group = "androidx.compose.ui", name = "ui-graphics" }
ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
ui-test-manifest = { group = "androidx.compose.ui", name = "ui-test-manifest" }
ui-test-junit4 = { group = "androidx.compose.ui", name = "ui-test-junit4" }
material3 = { group = "androidx.compose.material", name = "material" }
dagger-hilt = { group = "com.google.dagger", name = "hilt-android", version.ref = "dagger" }
dagger-hilt-navigation = { group = "androidx.hilt", name = "hilt-navigation-compose", version = "1.0.0" }
dagger-hilt-kapt = { group = "com.google.dagger", name = "hilt-compiler", version = "2.45" }
navigation-compose = { group = "androidx.navigation", name = "navigation-compose", version.ref = "navigation" }
moshi-kotlin = { group = "com.squareup.moshi", name = "moshi", version.ref = "moshi" }
moshi-kotlin-codegen = { group = "com.squareup.moshi", name = "moshi-kotlin-codegen", version.ref = "moshi" }
material-icons-extended = { group = "androidx.compose.material", name = "material-icons-extended", version.ref = "extended-icons" }
compose-material = { group = "androidx.compose.material", name = "material" }
viewmodel-compose = { group = "androidx.lifecycle", name = "lifecycle-viewmodel-compose", version = "2.6.1" }
system-uicontroller = { group = "com.google.accompanist", name = "accompanist-systemuicontroller", version.ref = "accompanist" }
permissions = { group = "com.google.accompanist", name = "accompanist-permissions", version.ref = "accompanist" }
location-services = { group = "com.google.android.gms", name = "play-services-location", version = "21.0.1" }
camera-android = { group = "androidx.camera", name = "camera-camera2", version.ref = "camera" }
camera-lifecycle = { group = "androidx.camera", name = "camera-lifecycle", version.ref = "camera" }
camera-view = { group = "androidx.camera", name = "camera-view", version = "1.3.0-alpha07" }
camera-core = { group = "androidx.camera", name = "camera-core", version.ref = "camera-core" }
camera-camera2 = { group = "androidx.camera", name = "camera-camera2", version.ref = "camera-core" }
google-mlkit = { group = "com.google.mlkit", name = "barcode-scanning", version.ref = "mlkit" }


pager = { group = "com.google.accompanist", name = "accompanist-pager", version.ref = "pager" }
androidx-material3 = { group = "androidx.compose.material", name = "material", version.ref = "material3" }
play-services-auth = { group = "com.google.android.gms", name = "play-services-auth", version.ref = "play-services-auth" }
firebase-auth-ktx = { group = "com.google.firebase", name = "firebase-auth-ktx", version.ref = "firebase-auth-ktx" }
firebase-firestore-ktx = { group = "com.google.firebase", name = "firebase-firestore-ktx", version.ref = "firebase-firestore-ktx" }

[plugins]
androidApplication = { id = "com.android.application", version.ref = "agp" }
kotlinAndroid = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }

[bundles]
